openapi: 3.0.3
info:
  title: Echo Service API
  description: A simple API that echoes back request information
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /:
    get:
      summary: Echo endpoint (GET)
      description: Returns a response containing a message and timestamp
      operationId: echoGet
      security:
        - default: []
      
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/json, application/json"
    post:
      summary: Echo endpoint (POST)
      description: Returns a response containing a message and timestamp
      operationId: echoPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/json, application/json"
    put:
      summary: Echo endpoint (PUT)
      description: Returns a response containing a message and timestamp
      operationId: echoPut
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/json, application/json"
    delete:
      summary: Echo endpoint (DELETE)
      description: Returns a response containing a message and timestamp
      operationId: echoDelete
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/json, application/json"

components:
  schemas:
    EchoResponse:
      type: object
      required:
        - message
        - timestamp
      properties:
        message:
          type: string
          example: "Echo service received your request"
        timestamp:
          type: string
          format: date-time
          example: "2025-08-19T10:00:00Z"
